### ISSUE TITLE
Could not resolve me.carda:fcmandroidcore:0.7.6 on android

### ISSUE THREAD

**Issue by radroot1** [rafaelsetragni/awesome_notifications_fcm#19]
## **1 - Describe the bug**

Trying to run app with awesome_notifications_fcm: 0.7.4+1, getting 521 from jitpack.io

## **2 - Provide us as much information as possible**

```
Could not resolve me.carda:fcmandroidcore:0.7.6.
         > Could not get resource 'https://jitpack.io/me/carda/fcmandroidcore/0.7.6/fcmandroidcore-0.7.6.pom'.
            > Could not GET 'https://jitpack.io/me/carda/fcmandroidcore/0.7.6/fcmandroidcore-0.7.6.pom'. Received status code 521 from server: 
```

## **3 - How To Reproduce the Error**

-Run or build app on android

**Comment by rafaelsetragni** [comment]
Just try again. This is an instability on jitpack.io server repository and is probably solved now.

**Comment by radroot1** [comment]
Still an error, 
https://jitpack.io/me/carda/fcmandroidcore/0.7.6/fcmandroidcore-0.7.6.pom
Strange that other packages from jitpack is resolvable, like https://jitpack.io/me/carda/androidcore/0.7.7/androidcore-0.7.7.aar

Is there some other way to get fcmandroidcore packages?

**Comment by rafaelsetragni** [comment]
No, i only updated it to jitpack.
